### ISSUE TITLE
Notes menu - multiple texts

### ISSUE THREAD

**Issue by dapgo** [enaon/ninebot-one-nRF52#2]
Feature to store display/notes 

**User case1: (Send and display)**

1. User from a BLE app,  send a Note to the smartwatch
i.e. through a command like: 
   _AT+PUSH=NOTE,1,"txt_note1"   or AT+PUSH=NOTE1,"txt_note1"_
(note that txt_note1 can contain separator symbol  or comma ",")

2.  Smartwatch software identifies that it is a note, and stores on slot x (1) 
3.  A user, from Smartwatch Menus,  click on "Notes"
4.  Smartwatch screen displays  Note1 (several lines of text)

**User case2: (Moving through multiple notes)**
1.  A user, from Smartwatch Menus,  click on "Notes"
2.  Smartwatch screen displays  Note1 (several lines of text)
3.  User can move to next Note (slot+1) if exists, or to previous Note (slot-1)

**User case4: (Overwrite/replace an existing note)**
1.  User from a BLE app,  send a new note to the smartwatch to overwrite a slot (i.e. note1) 
      _i.e AT+PUSH=NOTE,1,"newtxt_to_replace_note1"_

**Comment by enaon** [comment]
this is now supported:

AT+PUSH=8,Note_name,note body,3"

the leading 8 indicates a note, the last number is the note slot. Leave the note_body empty to delete the note.
